#!/bin/sh

LINUX_LOGO=../../linux_logo-4.08/linux_logo

for NAME in s390* ; do 

   $LINUX_LOGO -g -e $NAME > test 

   diff -u test ./known_good/$NAME.good

   RESULT=$?

   if [ $RESULT -gt 0 ]; then
       echo $NAME Failed
       exit
   fi
		

done

rm test
